name: Members
on:
  schedule:
    - cron:  '*/60 * * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn -p
      - name: Run Action
        env:
          LEARN_GH_TOKEN: ${{ secrets.LEARN_GH_TOKEN }}
        run: yarn run articles
